import type { ThemeDefinition } from "@/themes/types";

export const themes: ThemeDefinition[] = [
  {
    id: "voxel",
    name: "Voxel 3D",
    description: "Interactive 3D voxel world with Three.js",
    preview: "🧊",
    defaultPaletteId: "indigo-rose",
    bodyClassName: "grid-bg",
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism",
    description: "Frosted glass with depth and blur effects",
    preview: "🪟",
    defaultPaletteId: "violet-pink",
  },
  {
    id: "neon-cyberpunk",
    name: "Neon Cyberpunk",
    description: "Dark neon glow with cyberpunk aesthetics",
    preview: "🌃",
    defaultPaletteId: "cyan-magenta",
  },
  {
    id: "retro-pixel",
    name: "Retro Pixel",
    description: "8-bit pixel art with retro color palette",
    preview: "👾",
    defaultPaletteId: "warm-earth",
  },
  {
    id: "minimal",
    name: "Minimal Clean",
    description: "Clean typography with generous whitespace",
    preview: "✨",
    defaultPaletteId: "monochrome",
  },
  {
    id: "gradient-mesh",
    name: "Gradient Mesh",
    description: "Vibrant gradient blobs and organic shapes",
    preview: "🎨",
    defaultPaletteId: "purple-teal",
  },
  {
    id: "aurora",
    name: "Aurora Borealis",
    description: "Northern lights with ethereal glow animations",
    preview: "🌌",
    defaultPaletteId: "arctic-cyan",
  },
  // ── New themes ──
  {
    id: "particles",
    name: "Particles",
    description: "Floating particle system with connecting lines",
    preview: "✦",
    defaultPaletteId: "ocean-deep",
  },
  {
    id: "brutalist",
    name: "Brutalist",
    description: "Raw, bold typography with hard edges",
    preview: "🏗️",
    defaultPaletteId: "monochrome",
  },
  {
    id: "neumorphism",
    name: "Neumorphism",
    description: "Soft shadows and embossed surfaces",
    preview: "🫧",
    defaultPaletteId: "frost",
  },
  {
    id: "terminal",
    name: "Terminal",
    description: "Hacker terminal with monospace aesthetics",
    preview: "💻",
    defaultPaletteId: "neon-lime",
  },
  {
    id: "isometric",
    name: "Isometric",
    description: "Isometric grid with geometric shapes",
    preview: "🔷",
    defaultPaletteId: "electric-blue",
  },
  {
    id: "watercolor",
    name: "Watercolor",
    description: "Soft watercolor washes on paper texture",
    preview: "🖌️",
    defaultPaletteId: "lavender-dream",
  },
  {
    id: "geometric",
    name: "Geometric",
    description: "Abstract geometric shapes and patterns",
    preview: "🔺",
    defaultPaletteId: "candy-pop",
  },
  {
    id: "newspaper",
    name: "Newspaper",
    description: "Classic editorial layout with serif typography",
    preview: "📰",
    defaultPaletteId: "monochrome",
  },
  {
    id: "synthwave",
    name: "Synthwave",
    description: "80s retro sunset with neon grid and chrome",
    preview: "🌆",
    defaultPaletteId: "sunset-blaze",
  },
  {
    id: "zen",
    name: "Zen",
    description: "Minimalist Japanese-inspired calm aesthetics",
    preview: "🍵",
    defaultPaletteId: "mint-fresh",
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Technical blueprint with grid lines and wireframes",
    preview: "📐",
    defaultPaletteId: "ocean-deep",
  },
  {
    id: "topography",
    name: "Topography",
    description: "Contour map lines with elevation markers",
    preview: "🗺️",
    defaultPaletteId: "forest-emerald",
  },
  {
    id: "circuit",
    name: "Circuit Board",
    description: "PCB traces, IC chips, and signal paths",
    preview: "🔌",
    defaultPaletteId: "neon-lime",
  },
  {
    id: "origami",
    name: "Origami",
    description: "Paper fold aesthetics with soft creases",
    preview: "🦢",
    defaultPaletteId: "warm-sand",
  },
  {
    id: "stained-glass",
    name: "Stained Glass",
    description: "Colorful mosaic panels with lead-line borders",
    preview: "🏰",
    defaultPaletteId: "royal-purple",
  },
  {
    id: "marble",
    name: "Marble",
    description: "Elegant marble veins with gold accents",
    preview: "🏛️",
    defaultPaletteId: "warm-sand",
  },
  {
    id: "constellation",
    name: "Constellation",
    description: "Star maps with connecting constellation lines",
    preview: "⭐",
    defaultPaletteId: "deep-space",
  },
  {
    id: "dna-helix",
    name: "DNA Helix",
    description: "Biotech double helix with molecular nodes",
    preview: "🧬",
    defaultPaletteId: "arctic-cyan",
  },
  {
    id: "art-deco",
    name: "Art Deco",
    description: "1920s geometric elegance with gold accents",
    preview: "🎭",
    defaultPaletteId: "midnight-gold",
  },
  {
    id: "matrix-rain",
    name: "Matrix Rain",
    description: "Falling code rain with green phosphor glow",
    preview: "🟢",
    defaultPaletteId: "toxic-green",
  },
  {
    id: "coral-reef",
    name: "Coral Reef",
    description: "Underwater coral branches with floating bubbles",
    preview: "🐠",
    defaultPaletteId: "ocean-deep",
  },
  {
    id: "sand-dunes",
    name: "Sand Dunes",
    description: "Desert landscape with warm golden gradients",
    preview: "🏜️",
    defaultPaletteId: "copper-rust",
  },
  {
    id: "cassette",
    name: "Cassette",
    description: "Retro mixtape with VU meters and tape reels",
    preview: "📼",
    defaultPaletteId: "warm-earth",
  },
  {
    id: "hologram",
    name: "Hologram",
    description: "Sci-fi holographic projections with flicker",
    preview: "🔮",
    defaultPaletteId: "arctic-cyan",
  },
];

export type ThemeId = (typeof themes)[number]["id"];

export function getThemeById(id: string): ThemeDefinition | undefined {
  return themes.find((t) => t.id === id);
}

export const DEFAULT_THEME_ID = "voxel";
